### ISSUE TITLE
Правки в админпанель

### ISSUE THREAD

**Issue by behjke** [MiigaikUI/MiigaikCRM#17]
- [x] Добавить отображение недель в фильтр при просмотре страницы "Пары в расписании"
- [x] Добавить возможность выбирать недели из 2023 года (до марта)
- [ ] Добавить возможность выбирать тип предмета (лекция, пара и т.д.) при добавлении пары в расписании (множественный выбор) 
- [ ] Добавить возможность выбирать несколько групп при добавлении пары в расписании (множественный выбор)

**Comment by I-SMAF** [comment]
- - [X] Добавить возможность выбирать тип предмета (лекция, пара и т.д.) при добавлении пары в расписании (множественный выбор)  - **НЕТ ВОЗМОЖНОСТИ БЕСШОВНОГО СОХРАНЕНИЯ ПРЕДЫДУЩЕЙ ЗАПИСИ**
- - [X] Добавить возможность выбирать несколько групп при добавлении пары в расписании (множественный выбор) - **НЕТ ВОЗМОЖНОСТИ БЕСШОВНОГО СОХРАНЕНИЯ ПРЕДЫДУЩЕЙ ЗАПИСИ**
